  apiVersion: argoproj.io/v1alpha1
  kind: Workflow
  metadata:
    generateName: llm-train-
  spec:
    entrypoint: train-llm
    templates:
      - name: train-llm
        container:
          image: pr0tex/trainer:v1.5
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 6Gi
              cpu: "4"
    podSpecPatch: |
      containers:
      - name: main
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
