apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server
  namespace: gpu-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-server
  template:
    metadata:
      labels:
        app: llm-server
    spec:
      runtimeClassName: nvidia
      containers:
      - name: llm
        image: nvidia/cuda:12.3.2-base-ubuntu22.04
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update && apt-get install -y python3 python3-pip git curl &&
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 &&
            pip install transformers fastapi uvicorn &&
            cd /app &&
            uvicorn main:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: llm-code
          mountPath: /app
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: llm-code
        hostPath:
          path: /opt/llm-server
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: gpu-setup
spec:
  selector:
    app: llm-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
