apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: llm-train-
spec:
  entrypoint: train-llm
  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: llm-model-pvc

  templates:
    - name: train-llm
      container:
        image: pr0tex/trainer:v1.6-250
        command: ["python3"]
        args: ["train.py"]
        volumeMounts:
          - name: model-volume
            mountPath: /app/model
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 6Gi
            cpu: "4"
      nodeSelector:
        node-type: gpu

  podSpecPatch: |
    runtimeClassName: nvidia
    containers:
    - name: main
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
