apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: llm-train-eval-register-
spec:
  entrypoint: full-ml-pipeline
  templates:
    - name: full-ml-pipeline
      steps:
        - - name: train-step
            template: train
        - - name: evaluate-step
            template: evaluate
            arguments:
              artifacts:
                - name: trained-model
                  from: "{{steps.train-step.outputs.artifacts.trained-model}}"
        - - name: register-step
            template: register
            arguments:
              artifacts:
                - name: trained-model
                  from: "{{steps.train-step.outputs.artifacts.trained-model}}"
    - name: train
      container:
        image: protex/llm-trainer:latest
        command: ["python3"]
        args: ["train.py"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 8Gi
            cpu: "4"
      outputs:
        artifacts:
          - name: trained-model
            path: /app/model
      volumeMounts:
        - name: shared-volume
          mountPath: /app/model
        
    - name: evaluate
      container:
        image: protex/llm-evaluator:latest
        command: ["python3"]
        args: ["evaluate.py", "--model_dir", "/app/model"]
        volumeMounts:
          - name: shared-volume
            mountPath: /app/model
      inputs:
        artifacts:
          - name: trained-model
            path: /app/model


    - name: register
      container:
        image: protex/llm-mlflow-logger:latest
        command: ["python3"]
        args: ["register.py", "--model_dir", "/app/model"]
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow-tracking-server.default.svc.cluster.local:5000
      inputs:
        artifacts:
          - name: trained-model
            path: /app/model
      volumeMounts:
        - name: shared-volume
          mountPath: /app/model

  volumes:
    - name: shared-volume
      emptyDir: {}
  podSpecPatch: |
    containers:
    - name: main
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
