apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: llm-trainer
spec:
  serviceAccountName: argo-workflow
  entrypoint: full-workflow
  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: llm-model-pvc

  templates:
    - name: full-workflow
      steps:
        - - name: train-step
            template: train-llm
        - - name: push-step
            template: push-model

    - name: train-llm
      container:
        image: pr0tex/trainer:v1.6-250
        volumeMounts:
          - name: model-volume
            mountPath: /app/model
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 6Gi
            cpu: "4"
      nodeSelector:
        node-type: gpu

    - name: push-model
      container:
        image: pr0tex/push-model:v1.2.4
        volumeMounts:
          - name: model-volume
            mountPath: /app/model
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 6Gi
            cpu: "4"
      nodeSelector:
        node-type: gpu

  podSpecPatch: |
    runtimeClassName: nvidia
    containers:
    - name: main
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
